### ISSUE TITLE
gobject `__main__+ChromeGNOMEShell' doesn't support property `application_id'

### ISSUE THREAD

**Issue by glasserc** [nE0sIghT/chrome-gnome-shell-mirror#106]
I'm trying to set up my GNOME extensions on a computer running NixOS. I've set up the connector using some [NixOS-specific configuration](https://github.com/NixOS/nixpkgs/issues/47340). I'm running Firefox Nightly 78.0a1 (2020-05-12). Navigating to https://extensions.gnome.org/local/ produces an error message saying "An unexpected error occurred". In the browser console is this message:

```
stderr output from native app org.gnome.chrome_gnome_shell: /nix/store/xswsy4dys3ysgpn6ixwsn5179ai6irg6-python3.7-pygobject-3.34.0/lib/python3.7/site-packages/gi/types.py:220: Warning: g_param_spec_pool_lookup: assertion 'pool != NULL' failed
stderr output from native app org.gnome.chrome_gnome_shell:   _gi.type_register(cls, namespace.get('__gtype_name__'))
stderr output from native app org.gnome.chrome_gnome_shell: /nix/store/xswsy4dys3ysgpn6ixwsn5179ai6irg6-python3.7-pygobject-3.34.0/lib/python3.7/site-packages/gi/types.py:220: Warning: g_param_spec_pool_insert: assertion 'pool != NULL' failed
stderr output from native app org.gnome.chrome_gnome_shell:   _gi.type_register(cls, namespace.get('__gtype_name__'))
stderr output from native app org.gnome.chrome_gnome_shell: Traceback (most recent call last):
stderr output from native app org.gnome.chrome_gnome_shell:   File "/nix/store/1vz9z5p2bzi11fwsg5fzlg0hk8mlzbzl-chrome-gnome-shell-10.1/bin/.chrome-gnome-shell-wrapped", line 585, in <module>
stderr output from native app org.gnome.chrome_gnome_shell:     app = ChromeGNOMEShell(run_as_service)
stderr output from native app org.gnome.chrome_gnome_shell:   File "/nix/store/1vz9z5p2bzi11fwsg5fzlg0hk8mlzbzl-chrome-gnome-shell-10.1/bin/.chrome-gnome-shell-wrapped", line 63, in __init__
stderr output from native app org.gnome.chrome_gnome_shell:     else Gio.ApplicationFlags.IS_LAUNCHER | Gio.ApplicationFlags.HANDLES_OPEN
stderr output from native app org.gnome.chrome_gnome_shell: TypeError: gobject `__main__+ChromeGNOMEShell' doesn't support property `application_id'
```

**Comment by nE0sIghT** [comment]
Looks like your installation of chrome-gnome-shell is broken. I can not help you with NixOS - look to proper dbus configuration for chrome-gnome-shell.  
As reference take some classic distro like Debian.

NixOS community resources is better place to ask.

**Comment by glasserc** [comment]
Thank you, I reported it to the NixOS maintainers and they were able to reproduce it.
