### ISSUE TITLE
https://extensions.gnome.org/ reports native connector not detected

### ISSUE THREAD

**Issue by ghanoumessi** [nE0sIghT/chrome-gnome-shell-mirror#58]
having the famous issue native connector not detected but not on ubuntu ,on chrome OpenSUSE
can't find a solution!

**Comment by nE0sIghT** [comment]
Which browser? Is chrome-gnome-shell package installed?

**Comment by ghanoumessi** [comment]
using chrome
i guess yeah i have the gnome icon on my browser

**Comment by nE0sIghT** [comment]
GNOME icon in browser means you have browser extension installed.
As you noticed at extensions.gnome.org you also need native host connector. Usualy, chrome-gnome-shell package in your distro.

**Comment by ghanoumessi** [comment]
how to check  !

**Comment by nE0sIghT** [comment]
I'm not a OpenSUSE user. Try to ask at OpenSUSE forums or so.

**Comment by ghanoumessi** [comment]
hello,
so i've installed it and now i get this error when i enter to https://extensions.gnome.org/
Native host has exited.

**Comment by nE0sIghT** [comment]
@ghanoumessi run chromium from console and post output here

**Comment by ghanoumessi** [comment]
here it is : 
[20902:20933:0425/175234.540376:ERROR:nss_util.cc(808)] After loading Root Certs, loaded==false: NSS error code: -8018
[20988:20988:0425/175234.631456:ERROR:sandbox_linux.cc(343)] InitializeSandbox() called with multiple threads in process gpu-process. 
[20988:20988:0425/175234.632426:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 20, in <module>
    import requests
ImportError: No module named requests
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 20, in <module>
    import requests
ImportError: No module named requests
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 20, in <module>
    import requests
ImportError: No module named requests
[20902:21212:0425/175249.618859:ERROR:cert_verify_proc_nss.cc(918)] CERT_PKIXVerifyCert for epicunitscan.info failed err=-8181

**Comment by nE0sIghT** [comment]
@ghanoumessi 

```
ImportError: No module named requests
```
means you missing python-requests package

**Comment by ghanoumessi** [comment]
Ok bruh ,
i installed it and now it's working :D ^^

**Comment by nE0sIghT** [comment]
Glad to hear it works for you.
Closing then.
