### ISSUE TITLE
Native host has exited. Error in Debian 

### ISSUE THREAD

**Issue by Dacs95** [nE0sIghT/chrome-gnome-shell-mirror#63]
Hello, I'm trying to used the gnome extensions in chromium but it gave me "Native host has exited." error.
 When I open chromium from terminal it gave me the next errors: 

[10792:10792:0521/183545.391645:ERROR:browser_main_loop.cc(279)] Gtk: Imposible encontrar el motor de temas en la ruta al _modulo: «murrine»,
[10792:10792:0521/183545.391732:ERROR:browser_main_loop.cc(279)] Gtk: Imposible encontrar el motor de temas en la ruta al _modulo: «murrine»,
[10792:10792:0521/183545.391805:ERROR:browser_main_loop.cc(279)] Gtk: Imposible encontrar el motor de temas en la ruta al _modulo: «murrine»,

My OS is debian.

**Comment by nE0sIghT** [comment]
Hello.

1. Edit /usr/bin/chrome-gnome-shell as root user and change
```DEBUG_ENABLED = False```
to
```DEBUG_ENABLED = True```
2. Close all Chromium windows/processes
3. Open Chromium from terminal and post output here

**Comment by Dacs95** [comment]
Hello again, the output was: 

[2884:2884:0522/113603.318078:ERROR:browser_main_loop.cc(279)] Gtk: Imposible encontrar el motor de temas en la ruta al _modulo: «murrine»,
[2884:2884:0522/113603.327511:ERROR:browser_main_loop.cc(279)] Gtk: Imposible encontrar el motor de temas en la ruta al _modulo: «murrine»,
[2884:2884:0522/113603.327638:ERROR:browser_main_loop.cc(279)] Gtk: Imposible encontrar el motor de temas en la ruta al _modulo: «murrine»,
[2884:2911:0522/113604.517110:ERROR:nss_util.cc(808)] After loading Root Certs, loaded==false: NSS error code: -8018
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 20, in <module>
    import requests
ImportError: No module named requests
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 20, in <module>
    import requests
ImportError: No module named requests

**Comment by nE0sIghT** [comment]
You should install Python requests 2.x (usualy named "python-requests", "python2-requests" or "python3-requests" in distros) as [stated in the wiki](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation#Cmake_installation).
If you installed chrome-gnome-shell using distro package - report this issue to distro package maintainer.
